servers:
  - name: "product"
    host: "http://product.api:3000"
    prefix: "/product"
    port: 3000
    api_key: "uit39t8tvjwrfj05ldsf-0"
  
  - name: "vendor"
    host: "http://vendor.api:3001"
    prefix: "/vendor"
    port: 3001
    api_key: "sdfjfhasdjdf123ksmdf"